In [1]:
import numpy as np
import pandas as pd

In [2]:

flats = pd.read_csv('flats_cleaned.csv')
houses = pd.read_csv('house_cleaned.csv')

In [3]:
df = pd.concat([flats,houses],ignore_index=True)

In [4]:
# ramdomness
df = df.sample(df.shape[0],ignore_index=True)

In [5]:
df.head()

,Unnamed: 0,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,...,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2766.0,3 BHK Flat in Dwarka Expressway Gurgaon,flat,Ansals Highland Park,1.20,6185.0,1940.0,Built Up area: 1940 (180.23 sq.m.),3,3,...,servant room,"Sector 103, Dwarka Expressway, Gurugram, Harya...",4.0,NaN,Under Construction,"['Dr. Hitesh Dawar', 'Bhardwaj Hospital', 'R K...",This three bedroom for sale comes with an affo...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...",NaN,NaN
1,306.0,4 BHK Flat in Sector 86 Gurgaon,flat,Ansal Heights 86,1.30,4666.0,2786.0,Super Built up area 2786(258.83 sq.m.),4,6,...,"servant room,others","11 Th Floor, Sector 86 Gurgaon, Gurgaon, Haryana",11.0,East,0 to 1 Year Old,"['IRIS Broadway Mall', 'Delhi Jaipur Expresswa...",Ready to move property directly available from...,NaN,"['Security / Fire Alarm', 'Lift(s)', 'Maintena...","['Connectivity4.5 out of 5', 'Lifestyle5 out o..."
2,2176.0,3 BHK Flat in Sector 51 Gurgaon,flat,Orchid Island4.2 ★,1.70,10651.0,1596.0,Carpet area: 1596 (148.27 sq.m.),3,4,...,"pooja room,store room","Sector 51 Gurgaon, Gurgaon, Haryana",2.0,West,5 to 10 Year Old,"['Rapid Metro Sector 55-56', 'Tigra Market', '...",It's one of the huge lowrise society with mass...,"['4 Geyser', '10 Light', '4 AC', 'No Bed', 'No...","['Power Back-up', 'Private Garden / Terrace', ...","['Green Area5 out of 5', 'Construction4.5 out ..."
3,1450.0,2 BHK Flat in Sohna,flat,Signature Global Park4.0 ★,0.72,5991.0,1202.0,Super Built up area 1210(112.41 sq.m.),2,2,...,pooja room,"001, Sohna, Gurgaon, Haryana",3.0,North-West,1 to 5 Year Old,"['Sector 55-56 metro', 'Global city centre', '...","Signature global park in sohna, gurgaon is a r...","['3 Fan', '1 Exhaust Fan', '3 Light', '1 Modul...","['Water purifier', 'Centrally Air Conditioned'...","['Green Area5 out of 5', 'Construction5 out of..."
4,NaN,5 Bedroom House for sale in Sector 112 Gurgaon,house,experion windchants,9.50,23457.0,4050.0,Plot area 450(376.26 sq.m.)Built Up area: 7450...,5,5,...,servant room,"Sector 112 Gurgaon, Gurgaon, Haryana",2.0,NaN,1 to 5 Year Old,"['Ansal Plaza', 'Dwaraka Expressway', 'First S...","Sector 112 gurgaon, gurgaon, haryana\nKindly c...","['1 Modular Kitchen', 'No AC', 'No Bed', 'No C...","['Maintenance Staff', 'Swimming Pool', 'Park',...","['Environment5 out of 5', 'Lifestyle4 out of 5..."

In [6]:
df.to_csv('gurgaon_properties.csv',index=False)

In [7]:
df.shape

(3961, 21)